# Generated by Django 6.0.5 on 2026-07-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0008_violationsnapshot_gaze_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='idverificationattempt',
            name='notes',
            field=models.TextField(blank=True, help_text='Why the round ended this way — shown to staff in the audit trail.'),
        ),
        migrations.AddField(
            model_name='idverificationattempt',
            name='outcome',
            field=models.CharField(blank=True, help_text='match, no_match, no_face or unavailable.', max_length=20),
        ),
        migrations.AddField(
            model_name='proctoringsession',
            name='id_verification_faults',
            field=models.PositiveIntegerField(default=0, help_text='Rounds that could not produce a comparison (no face, model or reference unavailable).'),
        ),
        migrations.AddField(
            model_name='proctoringsession',
            name='last_id_outcome',
            field=models.CharField(blank=True, help_text='Outcome of the most recent identity round: match, no_match, no_face, unavailable.', max_length=20),
        ),
        migrations.AlterField(
            model_name='proctoringsession',
            name='id_verification_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Conclusive face comparisons only — system faults are not counted.'),
        ),
        migrations.AlterField(
            model_name='proctoringsession',
            name='id_verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('unverified', 'Admitted Without Face Match')], default='pending', max_length=20),
        ),
    ]
