# Generated by Django 6.0.5 on 2026-09-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0009_idverificationattempt_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringsession',
            name='id_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
